version: '3'
services:

    jupyter:
        # the image tag python-3.9.2 is not working on Mac, this tga works
        image: jupyter/scipy-notebook:33add21fab64
        container_name: jupyter
        ports:
        - "8888:8888"
        volumes:
        - ".:/home/jovyan/work"
