version: '3'
services:

    jupyter:
        image: jupyter/scipy-notebook:python-3.9.2
        container_name: jupyter
        ports:
        - "8888:8888"
        volumes:
        - ".:/home/jovyan/work"
